source 'https://supermarket.chef.io'
source chef_repo: ".."

metadata

# Mu Cookbooks

# Supermarket Cookbooks
cookbook 'windows', '~> 5.1.1'
cookbook 'firewall', '~> 2.8.0', git: "https://github.com/cloudamatic/firewall.git"